kind: pipeline
type: docker
name: default

steps:
- name: clean
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  commands:
  - dotnet --version
  - dotnet clean Drone-POC/Core/Core.csproj

- name: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  commands:
  - dotnet build Drone-POC/Core/Core.csproj
