kind: pipeline
type: docker
name: default

steps:
- name: clean and build
  image: microsoft/dotnetcore:sdk
  commands:
  - dotnet clean Drone-POC/Core/Core.csproj
  - dotnet build Drone-POC/Core/Core.csproj
