kind: pipeline
type: docker
name: default

steps:
- name: clean
  image: microsoft/dotnet:2.1-aspnetcore-runtime
  commands:
  - dotnet clean Drone-POC/Core/Core.csproj

- name: build
  image: microsoft/core-nightly:sdk
  commands:
  - dotnet build Drone-POC/Core/Core.csproj
